apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-bnwwzadf
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-bnwwzadf:5a6e702a5edb66af34e89421eccf29200d9a89ba@sha256:4c2ed4963dda485605a4c450390caa807dab19a446f21a6219749e52fa7ddf58
          name: container-image
